/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAdminRole,
  IAdminRoleInterface,
} from "../../../contracts/interfaces/IAdminRole";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAdminRole__factory {
  static readonly abi = _abi;
  static createInterface(): IAdminRoleInterface {
    return new utils.Interface(_abi) as IAdminRoleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAdminRole {
    return new Contract(address, _abi, signerOrProvider) as IAdminRole;
  }
}
