/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRoles,
  IRolesInterface,
} from "../../../contracts/interfaces/IRoles";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isOperator",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRoles__factory {
  static readonly abi = _abi;
  static createInterface(): IRolesInterface {
    return new utils.Interface(_abi) as IRolesInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IRoles {
    return new Contract(address, _abi, signerOrProvider) as IRoles;
  }
}
