/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace ExchangeAuction {
  export type AuctionStruct = {
    nftContract: string;
    tokenId: BigNumberish;
    seller: string;
    startTime: BigNumberish;
    endTime: BigNumberish;
    bidder: string;
    amount: BigNumberish;
  };

  export type AuctionStructOutput = [
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber
  ] & {
    nftContract: string;
    tokenId: BigNumber;
    seller: string;
    startTime: BigNumber;
    endTime: BigNumber;
    bidder: string;
    amount: BigNumber;
  };
}

export interface CassavaLandExchangeInterface extends utils.Interface {
  functions: {
    "acceptOffer(address,uint256,address,uint256)": FunctionFragment;
    "bid(uint256,uint256)": FunctionFragment;
    "buy(address,uint256,uint256,uint256,address)": FunctionFragment;
    "cancelAuction(uint256)": FunctionFragment;
    "cancelBuyPrice(address,uint256,uint256)": FunctionFragment;
    "createAuction(address,uint256,uint256,uint256,uint256)": FunctionFragment;
    "defaultTreasury()": FunctionFragment;
    "finalizeAuction(uint256)": FunctionFragment;
    "getAuction(uint256)": FunctionFragment;
    "getAuctionIdFor(address,uint256)": FunctionFragment;
    "getBuyNowPrice(address,uint256)": FunctionFragment;
    "getMinBidAmount(uint256)": FunctionFragment;
    "getMinOfferAmount(address,uint256)": FunctionFragment;
    "getOffer(address,uint256)": FunctionFragment;
    "getWtfuelAddress()": FunctionFragment;
    "makeOffer(address,uint256,uint256)": FunctionFragment;
    "protocolFee()": FunctionFragment;
    "rolesManager()": FunctionFragment;
    "setBuyPrice(address,uint256,uint256,uint256)": FunctionFragment;
    "setDefaultTreasury(address)": FunctionFragment;
    "setProtocolFee(uint256)": FunctionFragment;
    "setTokenTreasury(address,address)": FunctionFragment;
    "treasuries(address)": FunctionFragment;
    "updateAuction(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptOffer"
      | "bid"
      | "buy"
      | "cancelAuction"
      | "cancelBuyPrice"
      | "createAuction"
      | "defaultTreasury"
      | "finalizeAuction"
      | "getAuction"
      | "getAuctionIdFor"
      | "getBuyNowPrice"
      | "getMinBidAmount"
      | "getMinOfferAmount"
      | "getOffer"
      | "getWtfuelAddress"
      | "makeOffer"
      | "protocolFee"
      | "rolesManager"
      | "setBuyPrice"
      | "setDefaultTreasury"
      | "setProtocolFee"
      | "setTokenTreasury"
      | "treasuries"
      | "updateAuction"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOffer",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [string, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBuyPrice",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionIdFor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyNowPrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinBidAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinOfferAmount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWtfuelAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "makeOffer",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rolesManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBuyPrice",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultTreasury",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenTreasury",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "treasuries", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateAuction",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAuction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionIdFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyNowPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinBidAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinOfferAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWtfuelAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "makeOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rolesManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasuries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAuction",
    data: BytesLike
  ): Result;

  events: {
    "AuctionCancelled(uint256)": EventFragment;
    "AuctionCreated(address,address,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "AuctionFinalized(uint256,address,address,uint256,uint256,uint256)": EventFragment;
    "AuctionInvalidated(uint256)": EventFragment;
    "AuctionUpdated(uint256,uint256)": EventFragment;
    "BuyPriceAccepted(address,uint256,address,address,uint256,uint256,uint256)": EventFragment;
    "BuyPriceCanceled(address,uint256)": EventFragment;
    "BuyPriceInvalidated(address,uint256)": EventFragment;
    "BuyPriceSet(address,uint256,address,uint256)": EventFragment;
    "NewBid(uint256,address,uint256,uint256)": EventFragment;
    "NewOffer(address,uint256,address,uint256,uint256)": EventFragment;
    "OfferAccepted(address,uint256,address,address,uint256,uint256,uint256)": EventFragment;
    "OfferCancelledByAdmin(address,uint256,string)": EventFragment;
    "OfferInvalidated(address,uint256)": EventFragment;
    "TransferProxyUpdated(string,address)": EventFragment;
    "TransferToWTfuelExchange(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuctionCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionFinalized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionInvalidated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyPriceAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyPriceCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyPriceInvalidated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyPriceSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewBid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferCancelledByAdmin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferInvalidated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferProxyUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferToWTfuelExchange"): EventFragment;
}

export interface AuctionCancelledEventObject {
  auctionId: BigNumber;
}
export type AuctionCancelledEvent = TypedEvent<
  [BigNumber],
  AuctionCancelledEventObject
>;

export type AuctionCancelledEventFilter =
  TypedEventFilter<AuctionCancelledEvent>;

export interface AuctionCreatedEventObject {
  seller: string;
  nftContract: string;
  tokenId: BigNumber;
  startTime: BigNumber;
  endTime: BigNumber;
  reservePrice: BigNumber;
  auctionId: BigNumber;
}
export type AuctionCreatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  AuctionCreatedEventObject
>;

export type AuctionCreatedEventFilter = TypedEventFilter<AuctionCreatedEvent>;

export interface AuctionFinalizedEventObject {
  auctionId: BigNumber;
  seller: string;
  bidder: string;
  protocolFeeAmount: BigNumber;
  royaltyAmount: BigNumber;
  ownerRevenue: BigNumber;
}
export type AuctionFinalizedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber, BigNumber],
  AuctionFinalizedEventObject
>;

export type AuctionFinalizedEventFilter =
  TypedEventFilter<AuctionFinalizedEvent>;

export interface AuctionInvalidatedEventObject {
  auctionId: BigNumber;
}
export type AuctionInvalidatedEvent = TypedEvent<
  [BigNumber],
  AuctionInvalidatedEventObject
>;

export type AuctionInvalidatedEventFilter =
  TypedEventFilter<AuctionInvalidatedEvent>;

export interface AuctionUpdatedEventObject {
  auctionId: BigNumber;
  reservePrice: BigNumber;
}
export type AuctionUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  AuctionUpdatedEventObject
>;

export type AuctionUpdatedEventFilter = TypedEventFilter<AuctionUpdatedEvent>;

export interface BuyPriceAcceptedEventObject {
  nftContract: string;
  tokenId: BigNumber;
  seller: string;
  buyer: string;
  protocolFee: BigNumber;
  royaltyFeeAmount: BigNumber;
  ownerRevenue: BigNumber;
}
export type BuyPriceAcceptedEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber, BigNumber, BigNumber],
  BuyPriceAcceptedEventObject
>;

export type BuyPriceAcceptedEventFilter =
  TypedEventFilter<BuyPriceAcceptedEvent>;

export interface BuyPriceCanceledEventObject {
  nftContract: string;
  tokenId: BigNumber;
}
export type BuyPriceCanceledEvent = TypedEvent<
  [string, BigNumber],
  BuyPriceCanceledEventObject
>;

export type BuyPriceCanceledEventFilter =
  TypedEventFilter<BuyPriceCanceledEvent>;

export interface BuyPriceInvalidatedEventObject {
  nftContract: string;
  tokenId: BigNumber;
}
export type BuyPriceInvalidatedEvent = TypedEvent<
  [string, BigNumber],
  BuyPriceInvalidatedEventObject
>;

export type BuyPriceInvalidatedEventFilter =
  TypedEventFilter<BuyPriceInvalidatedEvent>;

export interface BuyPriceSetEventObject {
  nftContract: string;
  tokenId: BigNumber;
  seller: string;
  price: BigNumber;
}
export type BuyPriceSetEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  BuyPriceSetEventObject
>;

export type BuyPriceSetEventFilter = TypedEventFilter<BuyPriceSetEvent>;

export interface NewBidEventObject {
  auctionId: BigNumber;
  bidder: string;
  amount: BigNumber;
  endTime: BigNumber;
}
export type NewBidEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  NewBidEventObject
>;

export type NewBidEventFilter = TypedEventFilter<NewBidEvent>;

export interface NewOfferEventObject {
  nftContract: string;
  tokenId: BigNumber;
  buyer: string;
  amount: BigNumber;
  expiration: BigNumber;
}
export type NewOfferEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, BigNumber],
  NewOfferEventObject
>;

export type NewOfferEventFilter = TypedEventFilter<NewOfferEvent>;

export interface OfferAcceptedEventObject {
  nftContract: string;
  tokenId: BigNumber;
  buyer: string;
  seller: string;
  protocolFeeAmount: BigNumber;
  royaltyAmount: BigNumber;
  ownerRevenue: BigNumber;
}
export type OfferAcceptedEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber, BigNumber, BigNumber],
  OfferAcceptedEventObject
>;

export type OfferAcceptedEventFilter = TypedEventFilter<OfferAcceptedEvent>;

export interface OfferCancelledByAdminEventObject {
  nftContract: string;
  tokenId: BigNumber;
  reason: string;
}
export type OfferCancelledByAdminEvent = TypedEvent<
  [string, BigNumber, string],
  OfferCancelledByAdminEventObject
>;

export type OfferCancelledByAdminEventFilter =
  TypedEventFilter<OfferCancelledByAdminEvent>;

export interface OfferInvalidatedEventObject {
  nftContract: string;
  tokenId: BigNumber;
}
export type OfferInvalidatedEvent = TypedEvent<
  [string, BigNumber],
  OfferInvalidatedEventObject
>;

export type OfferInvalidatedEventFilter =
  TypedEventFilter<OfferInvalidatedEvent>;

export interface TransferProxyUpdatedEventObject {
  assetType: string;
  proxy: string;
}
export type TransferProxyUpdatedEvent = TypedEvent<
  [string, string],
  TransferProxyUpdatedEventObject
>;

export type TransferProxyUpdatedEventFilter =
  TypedEventFilter<TransferProxyUpdatedEvent>;

export interface TransferToWTfuelExchangeEventObject {
  user: string;
  amount: BigNumber;
}
export type TransferToWTfuelExchangeEvent = TypedEvent<
  [string, BigNumber],
  TransferToWTfuelExchangeEventObject
>;

export type TransferToWTfuelExchangeEventFilter =
  TypedEventFilter<TransferToWTfuelExchangeEvent>;

export interface CassavaLandExchange extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CassavaLandExchangeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOffer(
      nftContract: string,
      tokenId: BigNumberish,
      offerFrom: string,
      minAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    buy(
      nftContract: string,
      tokenId: BigNumberish,
      salePrice: BigNumberish,
      quantity: BigNumberish,
      paymentToken: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelBuyPrice(
      nftContract: string,
      tokenId: BigNumberish,
      quantity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createAuction(
      nftContract: string,
      tokenId: BigNumberish,
      reservePrice: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    defaultTreasury(overrides?: CallOverrides): Promise<[string]>;

    finalizeAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [ExchangeAuction.AuctionStructOutput] & {
        auction: ExchangeAuction.AuctionStructOutput;
      }
    >;

    getAuctionIdFor(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { auctionId: BigNumber }>;

    getBuyNowPrice(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { seller: string; salePrice: BigNumber }>;

    getMinBidAmount(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { minimum: BigNumber }>;

    getMinOfferAmount(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { minimum: BigNumber }>;

    getOffer(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        buyer: string;
        expiration: BigNumber;
        amount: BigNumber;
      }
    >;

    getWtfuelAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { wtfuelAddress: string }>;

    makeOffer(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    protocolFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    rolesManager(overrides?: CallOverrides): Promise<[string]>;

    setBuyPrice(
      nftContract: string,
      tokenId: BigNumberish,
      salePrice: BigNumberish,
      quantity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    updateAuction(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptOffer(
    nftContract: string,
    tokenId: BigNumberish,
    offerFrom: string,
    minAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bid(
    auctionId: BigNumberish,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  buy(
    nftContract: string,
    tokenId: BigNumberish,
    salePrice: BigNumberish,
    quantity: BigNumberish,
    paymentToken: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelAuction(
    auctionId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelBuyPrice(
    nftContract: string,
    tokenId: BigNumberish,
    quantity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createAuction(
    nftContract: string,
    tokenId: BigNumberish,
    reservePrice: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  defaultTreasury(overrides?: CallOverrides): Promise<string>;

  finalizeAuction(
    auctionId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAuction(
    auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<ExchangeAuction.AuctionStructOutput>;

  getAuctionIdFor(
    nftContract: string,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getBuyNowPrice(
    nftContract: string,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { seller: string; salePrice: BigNumber }>;

  getMinBidAmount(
    auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMinOfferAmount(
    nftContract: string,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getOffer(
    nftContract: string,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      buyer: string;
      expiration: BigNumber;
      amount: BigNumber;
    }
  >;

  getWtfuelAddress(overrides?: CallOverrides): Promise<string>;

  makeOffer(
    nftContract: string,
    tokenId: BigNumberish,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

  rolesManager(overrides?: CallOverrides): Promise<string>;

  setBuyPrice(
    nftContract: string,
    tokenId: BigNumberish,
    salePrice: BigNumberish,
    quantity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDefaultTreasury(
    _defaultTreasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProtocolFee(
    _protocolFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenTreasury(
    token: string,
    _treasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  treasuries(arg0: string, overrides?: CallOverrides): Promise<string>;

  updateAuction(
    auctionId: BigNumberish,
    reservePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOffer(
      nftContract: string,
      tokenId: BigNumberish,
      offerFrom: string,
      minAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    bid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    buy(
      nftContract: string,
      tokenId: BigNumberish,
      salePrice: BigNumberish,
      quantity: BigNumberish,
      paymentToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelBuyPrice(
      nftContract: string,
      tokenId: BigNumberish,
      quantity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createAuction(
      nftContract: string,
      tokenId: BigNumberish,
      reservePrice: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    defaultTreasury(overrides?: CallOverrides): Promise<string>;

    finalizeAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<ExchangeAuction.AuctionStructOutput>;

    getAuctionIdFor(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBuyNowPrice(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { seller: string; salePrice: BigNumber }>;

    getMinBidAmount(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinOfferAmount(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOffer(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        buyer: string;
        expiration: BigNumber;
        amount: BigNumber;
      }
    >;

    getWtfuelAddress(overrides?: CallOverrides): Promise<string>;

    makeOffer(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    rolesManager(overrides?: CallOverrides): Promise<string>;

    setBuyPrice(
      nftContract: string,
      tokenId: BigNumberish,
      salePrice: BigNumberish,
      quantity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<string>;

    updateAuction(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AuctionCancelled(uint256)"(
      auctionId?: BigNumberish | null
    ): AuctionCancelledEventFilter;
    AuctionCancelled(
      auctionId?: BigNumberish | null
    ): AuctionCancelledEventFilter;

    "AuctionCreated(address,address,uint256,uint256,uint256,uint256,uint256)"(
      seller?: string | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      startTime?: null,
      endTime?: null,
      reservePrice?: null,
      auctionId?: null
    ): AuctionCreatedEventFilter;
    AuctionCreated(
      seller?: string | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      startTime?: null,
      endTime?: null,
      reservePrice?: null,
      auctionId?: null
    ): AuctionCreatedEventFilter;

    "AuctionFinalized(uint256,address,address,uint256,uint256,uint256)"(
      auctionId?: BigNumberish | null,
      seller?: string | null,
      bidder?: string | null,
      protocolFeeAmount?: null,
      royaltyAmount?: null,
      ownerRevenue?: null
    ): AuctionFinalizedEventFilter;
    AuctionFinalized(
      auctionId?: BigNumberish | null,
      seller?: string | null,
      bidder?: string | null,
      protocolFeeAmount?: null,
      royaltyAmount?: null,
      ownerRevenue?: null
    ): AuctionFinalizedEventFilter;

    "AuctionInvalidated(uint256)"(
      auctionId?: BigNumberish | null
    ): AuctionInvalidatedEventFilter;
    AuctionInvalidated(
      auctionId?: BigNumberish | null
    ): AuctionInvalidatedEventFilter;

    "AuctionUpdated(uint256,uint256)"(
      auctionId?: BigNumberish | null,
      reservePrice?: null
    ): AuctionUpdatedEventFilter;
    AuctionUpdated(
      auctionId?: BigNumberish | null,
      reservePrice?: null
    ): AuctionUpdatedEventFilter;

    "BuyPriceAccepted(address,uint256,address,address,uint256,uint256,uint256)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      seller?: string | null,
      buyer?: null,
      protocolFee?: null,
      royaltyFeeAmount?: null,
      ownerRevenue?: null
    ): BuyPriceAcceptedEventFilter;
    BuyPriceAccepted(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      seller?: string | null,
      buyer?: null,
      protocolFee?: null,
      royaltyFeeAmount?: null,
      ownerRevenue?: null
    ): BuyPriceAcceptedEventFilter;

    "BuyPriceCanceled(address,uint256)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null
    ): BuyPriceCanceledEventFilter;
    BuyPriceCanceled(
      nftContract?: string | null,
      tokenId?: BigNumberish | null
    ): BuyPriceCanceledEventFilter;

    "BuyPriceInvalidated(address,uint256)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null
    ): BuyPriceInvalidatedEventFilter;
    BuyPriceInvalidated(
      nftContract?: string | null,
      tokenId?: BigNumberish | null
    ): BuyPriceInvalidatedEventFilter;

    "BuyPriceSet(address,uint256,address,uint256)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      seller?: string | null,
      price?: null
    ): BuyPriceSetEventFilter;
    BuyPriceSet(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      seller?: string | null,
      price?: null
    ): BuyPriceSetEventFilter;

    "NewBid(uint256,address,uint256,uint256)"(
      auctionId?: BigNumberish | null,
      bidder?: string | null,
      amount?: null,
      endTime?: null
    ): NewBidEventFilter;
    NewBid(
      auctionId?: BigNumberish | null,
      bidder?: string | null,
      amount?: null,
      endTime?: null
    ): NewBidEventFilter;

    "NewOffer(address,uint256,address,uint256,uint256)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null,
      amount?: null,
      expiration?: null
    ): NewOfferEventFilter;
    NewOffer(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null,
      amount?: null,
      expiration?: null
    ): NewOfferEventFilter;

    "OfferAccepted(address,uint256,address,address,uint256,uint256,uint256)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null,
      seller?: null,
      protocolFeeAmount?: null,
      royaltyAmount?: null,
      ownerRevenue?: null
    ): OfferAcceptedEventFilter;
    OfferAccepted(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null,
      seller?: null,
      protocolFeeAmount?: null,
      royaltyAmount?: null,
      ownerRevenue?: null
    ): OfferAcceptedEventFilter;

    "OfferCancelledByAdmin(address,uint256,string)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      reason?: null
    ): OfferCancelledByAdminEventFilter;
    OfferCancelledByAdmin(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      reason?: null
    ): OfferCancelledByAdminEventFilter;

    "OfferInvalidated(address,uint256)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null
    ): OfferInvalidatedEventFilter;
    OfferInvalidated(
      nftContract?: string | null,
      tokenId?: BigNumberish | null
    ): OfferInvalidatedEventFilter;

    "TransferProxyUpdated(string,address)"(
      assetType?: null,
      proxy?: null
    ): TransferProxyUpdatedEventFilter;
    TransferProxyUpdated(
      assetType?: null,
      proxy?: null
    ): TransferProxyUpdatedEventFilter;

    "TransferToWTfuelExchange(address,uint256)"(
      user?: string | null,
      amount?: null
    ): TransferToWTfuelExchangeEventFilter;
    TransferToWTfuelExchange(
      user?: string | null,
      amount?: null
    ): TransferToWTfuelExchangeEventFilter;
  };

  estimateGas: {
    acceptOffer(
      nftContract: string,
      tokenId: BigNumberish,
      offerFrom: string,
      minAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    buy(
      nftContract: string,
      tokenId: BigNumberish,
      salePrice: BigNumberish,
      quantity: BigNumberish,
      paymentToken: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelBuyPrice(
      nftContract: string,
      tokenId: BigNumberish,
      quantity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createAuction(
      nftContract: string,
      tokenId: BigNumberish,
      reservePrice: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    defaultTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    finalizeAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuctionIdFor(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBuyNowPrice(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinBidAmount(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinOfferAmount(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOffer(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWtfuelAddress(overrides?: CallOverrides): Promise<BigNumber>;

    makeOffer(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    rolesManager(overrides?: CallOverrides): Promise<BigNumber>;

    setBuyPrice(
      nftContract: string,
      tokenId: BigNumberish,
      salePrice: BigNumberish,
      quantity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    updateAuction(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOffer(
      nftContract: string,
      tokenId: BigNumberish,
      offerFrom: string,
      minAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    buy(
      nftContract: string,
      tokenId: BigNumberish,
      salePrice: BigNumberish,
      quantity: BigNumberish,
      paymentToken: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelBuyPrice(
      nftContract: string,
      tokenId: BigNumberish,
      quantity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createAuction(
      nftContract: string,
      tokenId: BigNumberish,
      reservePrice: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    defaultTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    finalizeAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAuctionIdFor(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBuyNowPrice(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinBidAmount(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinOfferAmount(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOffer(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWtfuelAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    makeOffer(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    protocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rolesManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setBuyPrice(
      nftContract: string,
      tokenId: BigNumberish,
      salePrice: BigNumberish,
      quantity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    treasuries(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateAuction(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
