/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface TransferManagerInterface extends utils.Interface {
  functions: {
    "defaultTreasury()": FunctionFragment;
    "getWtfuelAddress()": FunctionFragment;
    "protocolFee()": FunctionFragment;
    "rolesManager()": FunctionFragment;
    "setDefaultTreasury(address)": FunctionFragment;
    "setProtocolFee(uint256)": FunctionFragment;
    "setTokenTreasury(address,address)": FunctionFragment;
    "treasuries(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "defaultTreasury"
      | "getWtfuelAddress"
      | "protocolFee"
      | "rolesManager"
      | "setDefaultTreasury"
      | "setProtocolFee"
      | "setTokenTreasury"
      | "treasuries"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "defaultTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWtfuelAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rolesManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultTreasury",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenTreasury",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "treasuries", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "defaultTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWtfuelAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rolesManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasuries", data: BytesLike): Result;

  events: {
    "TransferProxyUpdated(string,address)": EventFragment;
    "TransferToWTfuelExchange(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TransferProxyUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferToWTfuelExchange"): EventFragment;
}

export interface TransferProxyUpdatedEventObject {
  assetType: string;
  proxy: string;
}
export type TransferProxyUpdatedEvent = TypedEvent<
  [string, string],
  TransferProxyUpdatedEventObject
>;

export type TransferProxyUpdatedEventFilter =
  TypedEventFilter<TransferProxyUpdatedEvent>;

export interface TransferToWTfuelExchangeEventObject {
  user: string;
  amount: BigNumber;
}
export type TransferToWTfuelExchangeEvent = TypedEvent<
  [string, BigNumber],
  TransferToWTfuelExchangeEventObject
>;

export type TransferToWTfuelExchangeEventFilter =
  TypedEventFilter<TransferToWTfuelExchangeEvent>;

export interface TransferManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TransferManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    defaultTreasury(overrides?: CallOverrides): Promise<[string]>;

    getWtfuelAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { wtfuelAddress: string }>;

    protocolFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    rolesManager(overrides?: CallOverrides): Promise<[string]>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<[string]>;
  };

  defaultTreasury(overrides?: CallOverrides): Promise<string>;

  getWtfuelAddress(overrides?: CallOverrides): Promise<string>;

  protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

  rolesManager(overrides?: CallOverrides): Promise<string>;

  setDefaultTreasury(
    _defaultTreasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProtocolFee(
    _protocolFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenTreasury(
    token: string,
    _treasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  treasuries(arg0: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    defaultTreasury(overrides?: CallOverrides): Promise<string>;

    getWtfuelAddress(overrides?: CallOverrides): Promise<string>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    rolesManager(overrides?: CallOverrides): Promise<string>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "TransferProxyUpdated(string,address)"(
      assetType?: null,
      proxy?: null
    ): TransferProxyUpdatedEventFilter;
    TransferProxyUpdated(
      assetType?: null,
      proxy?: null
    ): TransferProxyUpdatedEventFilter;

    "TransferToWTfuelExchange(address,uint256)"(
      user?: string | null,
      amount?: null
    ): TransferToWTfuelExchangeEventFilter;
    TransferToWTfuelExchange(
      user?: string | null,
      amount?: null
    ): TransferToWTfuelExchangeEventFilter;
  };

  estimateGas: {
    defaultTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    getWtfuelAddress(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    rolesManager(overrides?: CallOverrides): Promise<BigNumber>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    defaultTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWtfuelAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rolesManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    treasuries(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
