/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAdminRole } from "./IAdminRole";
export type { INftTransferProxy } from "./INftTransferProxy";
export type { IOperatorRole } from "./IOperatorRole";
export type { IOwnable } from "./IOwnable";
export type { IRoles } from "./IRoles";
export type { ITransferExecutor } from "./ITransferExecutor";
export type { IWTFUEL } from "./IWTFUEL";
