import {
  MdMenu,
  MdHelpOutline,
  MdClose,
  MdOutlineSearch,
  MdOutlineLightMode,
  MdOutlineDarkMode,
  MdCollections,
  MdOutlineNoPhotography,
  MdOutlineToys,
  MdLogout,
  MdSelectAll,
  MdOutlineAccountBalanceWallet,
  MdOutlineLanguage,
  MdOutlineExplore,
  MdCreateNewFolder,
  MdLocalOffer,
  MdOutlineHistory,
  MdMoreHoriz,
  MdVerified,
  MdEmail,
  MdAddCircle,
  MdModeEdit,
} from "react-icons/md";
import { RiInstagramFill } from "react-icons/ri";
import { BiUserCircle, BiArrowBack, BiTransfer, BiLink } from "react-icons/bi";
import {
  BsMedium,
  BsCheckLg,
  BsArrowDownLeft,
  BsArrowUpRight,
} from "react-icons/bs";
import { GiHeavyRain, GiMusicalScore, GiCheckMark } from "react-icons/gi";
import { ImInfo } from "react-icons/im";
import {
  IoDocumentOutline,
  IoGameControllerOutline,
  IoPeopleCircleOutline,
  IoPricetagSharp,
  IoTimeOutline,
  IoInfiniteSharp,
} from "react-icons/io5";
import {
  FaUserAlt,
  FaBlog,
  FaRegHeart,
  FaHeart,
  FaFacebookF,
  FaGithub,
  FaChevronRight,
  FaChevronLeft,
  FaChevronDown,
  FaChevronUp,
  FaCheckCircle,
  FaTwitter,
  FaDiscord,
  FaTelegramPlane,
  FaShoppingCart,
  FaExternalLinkAlt,
} from "react-icons/fa";
import {
  AiFillSetting,
  AiOutlineShareAlt,
  AiFillEdit,
  AiOutlineCloudUpload,
} from "react-icons/ai";

export {
  MdMenu as MenuIcon,
  MdHelpOutline as HelpIcon,
  BiUserCircle as UserCircleIcon,
  MdClose as CloseIcon,
  MdOutlineSearch as SearchIcon,
  MdOutlineLightMode as LightModeIcon,
  MdOutlineDarkMode as DarkModeIcon,
  MdCollections as CollectionsIcon,
  MdOutlineNoPhotography as PhotosIcon,
  MdOutlineToys as CollectiblesIcon,
  MdLogout as LogoutIcon,
  MdSelectAll as AllIcon,
  GiHeavyRain as ArtIcon,
  GiMusicalScore as MusicIcon,
  IoGameControllerOutline as GameIcon,
  FaUserAlt as UserIcon,
  FaRegHeart as FavouriteIcon,
  FaHeart as LoveIcon,
  AiFillSetting as SettingsIcon,
  FaBlog as BlogIcon,
  IoPeopleCircleOutline as CommunityIcon,
  IoDocumentOutline as DocsIcon,
  FaGithub as GithubIcon,
  MdOutlineAccountBalanceWallet as WalletIcon,
  MdOutlineLanguage as LanguageIcon,
  MdOutlineExplore as ExploreIcon,
  FaChevronRight as ChevronRightIcon,
  FaChevronLeft as ChevronLeftIcon,
  FaChevronDown as ChevronDownIcon,
  FaChevronUp as ChevronUpIcon,
  FaCheckCircle as CircleCheckIcon,
  FaTwitter as TwitterIcon,
  FaDiscord as DiscordIcon,
  FaTelegramPlane as TelegramIcon,
  BsMedium as MediumIcon,
  RiInstagramFill as InstagramIcon,
  BiArrowBack as BackArrowIcon,
  BsCheckLg as CheckMarkIcon,
  ImInfo as InfoIcon,
  FaFacebookF as FaceBookFIcon,
  AiOutlineShareAlt as ShareIcon,
  AiFillEdit as EditIcon,
  MdCreateNewFolder as FolderIcon,
  MdLocalOffer as OfferIcon,
  MdOutlineHistory as HistoryIcon,
  BsArrowDownLeft as ArrowDownLeftIcon,
  BsArrowUpRight as ArrowUpRightIcon,
  MdMoreHoriz as MoreIcon,
  MdVerified as VerifiedBadge,
  FaShoppingCart as ShoppingCartIcon,
  BiTransfer as TransferIcon,
  FaExternalLinkAlt as ExternalLinkIcon,
  IoPricetagSharp as SaleIcon,
  AiOutlineCloudUpload as UploadIcon,
  GiCheckMark as CheckIcon,
  IoTimeOutline as AuctionIcon,
  IoInfiniteSharp as OpenBidIcon,
  MdEmail as EmailIcon,
  BiLink as LinkIcon,
  MdAddCircle as AddCircleIcon,
  MdModeEdit as EditPencilIcon,
};
