/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export declare namespace ExchangeAuction {
  export type AuctionStruct = {
    nftContract: string;
    tokenId: BigNumberish;
    seller: string;
    startTime: BigNumberish;
    endTime: BigNumberish;
    bidder: string;
    amount: BigNumberish;
  };

  export type AuctionStructOutput = [
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber
  ] & {
    nftContract: string;
    tokenId: BigNumber;
    seller: string;
    startTime: BigNumber;
    endTime: BigNumber;
    bidder: string;
    amount: BigNumber;
  };
}

export interface ExchangeAuctionInterface extends utils.Interface {
  functions: {
    "bid(uint256,uint256)": FunctionFragment;
    "cancelAuction(uint256)": FunctionFragment;
    "createAuction(address,uint256,uint256,uint256,uint256)": FunctionFragment;
    "defaultTreasury()": FunctionFragment;
    "finalizeAuction(uint256)": FunctionFragment;
    "getAuction(uint256)": FunctionFragment;
    "getAuctionIdFor(address,uint256)": FunctionFragment;
    "getMinBidAmount(uint256)": FunctionFragment;
    "getWtfuelAddress()": FunctionFragment;
    "protocolFee()": FunctionFragment;
    "rolesManager()": FunctionFragment;
    "setDefaultTreasury(address)": FunctionFragment;
    "setProtocolFee(uint256)": FunctionFragment;
    "setTokenTreasury(address,address)": FunctionFragment;
    "treasuries(address)": FunctionFragment;
    "updateAuction(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "bid"
      | "cancelAuction"
      | "createAuction"
      | "defaultTreasury"
      | "finalizeAuction"
      | "getAuction"
      | "getAuctionIdFor"
      | "getMinBidAmount"
      | "getWtfuelAddress"
      | "protocolFee"
      | "rolesManager"
      | "setDefaultTreasury"
      | "setProtocolFee"
      | "setTokenTreasury"
      | "treasuries"
      | "updateAuction"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionIdFor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinBidAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWtfuelAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rolesManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultTreasury",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenTreasury",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "treasuries", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateAuction",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAuction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionIdFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinBidAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWtfuelAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rolesManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasuries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAuction",
    data: BytesLike
  ): Result;

  events: {
    "AuctionCancelled(uint256)": EventFragment;
    "AuctionCreated(address,address,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "AuctionFinalized(uint256,address,address,uint256,uint256,uint256)": EventFragment;
    "AuctionInvalidated(uint256)": EventFragment;
    "AuctionUpdated(uint256,uint256)": EventFragment;
    "NewBid(uint256,address,uint256,uint256)": EventFragment;
    "TransferProxyUpdated(string,address)": EventFragment;
    "TransferToWTfuelExchange(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuctionCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionFinalized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionInvalidated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewBid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferProxyUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferToWTfuelExchange"): EventFragment;
}

export interface AuctionCancelledEventObject {
  auctionId: BigNumber;
}
export type AuctionCancelledEvent = TypedEvent<
  [BigNumber],
  AuctionCancelledEventObject
>;

export type AuctionCancelledEventFilter =
  TypedEventFilter<AuctionCancelledEvent>;

export interface AuctionCreatedEventObject {
  seller: string;
  nftContract: string;
  tokenId: BigNumber;
  startTime: BigNumber;
  endTime: BigNumber;
  reservePrice: BigNumber;
  auctionId: BigNumber;
}
export type AuctionCreatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  AuctionCreatedEventObject
>;

export type AuctionCreatedEventFilter = TypedEventFilter<AuctionCreatedEvent>;

export interface AuctionFinalizedEventObject {
  auctionId: BigNumber;
  seller: string;
  bidder: string;
  protocolFeeAmount: BigNumber;
  royaltyAmount: BigNumber;
  ownerRevenue: BigNumber;
}
export type AuctionFinalizedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber, BigNumber],
  AuctionFinalizedEventObject
>;

export type AuctionFinalizedEventFilter =
  TypedEventFilter<AuctionFinalizedEvent>;

export interface AuctionInvalidatedEventObject {
  auctionId: BigNumber;
}
export type AuctionInvalidatedEvent = TypedEvent<
  [BigNumber],
  AuctionInvalidatedEventObject
>;

export type AuctionInvalidatedEventFilter =
  TypedEventFilter<AuctionInvalidatedEvent>;

export interface AuctionUpdatedEventObject {
  auctionId: BigNumber;
  reservePrice: BigNumber;
}
export type AuctionUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  AuctionUpdatedEventObject
>;

export type AuctionUpdatedEventFilter = TypedEventFilter<AuctionUpdatedEvent>;

export interface NewBidEventObject {
  auctionId: BigNumber;
  bidder: string;
  amount: BigNumber;
  endTime: BigNumber;
}
export type NewBidEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  NewBidEventObject
>;

export type NewBidEventFilter = TypedEventFilter<NewBidEvent>;

export interface TransferProxyUpdatedEventObject {
  assetType: string;
  proxy: string;
}
export type TransferProxyUpdatedEvent = TypedEvent<
  [string, string],
  TransferProxyUpdatedEventObject
>;

export type TransferProxyUpdatedEventFilter =
  TypedEventFilter<TransferProxyUpdatedEvent>;

export interface TransferToWTfuelExchangeEventObject {
  user: string;
  amount: BigNumber;
}
export type TransferToWTfuelExchangeEvent = TypedEvent<
  [string, BigNumber],
  TransferToWTfuelExchangeEventObject
>;

export type TransferToWTfuelExchangeEventFilter =
  TypedEventFilter<TransferToWTfuelExchangeEvent>;

export interface ExchangeAuction extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ExchangeAuctionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createAuction(
      nftContract: string,
      tokenId: BigNumberish,
      reservePrice: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    defaultTreasury(overrides?: CallOverrides): Promise<[string]>;

    finalizeAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [ExchangeAuction.AuctionStructOutput] & {
        auction: ExchangeAuction.AuctionStructOutput;
      }
    >;

    getAuctionIdFor(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { auctionId: BigNumber }>;

    getMinBidAmount(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { minimum: BigNumber }>;

    getWtfuelAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { wtfuelAddress: string }>;

    protocolFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    rolesManager(overrides?: CallOverrides): Promise<[string]>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    updateAuction(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  bid(
    auctionId: BigNumberish,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelAuction(
    auctionId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createAuction(
    nftContract: string,
    tokenId: BigNumberish,
    reservePrice: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  defaultTreasury(overrides?: CallOverrides): Promise<string>;

  finalizeAuction(
    auctionId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAuction(
    auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<ExchangeAuction.AuctionStructOutput>;

  getAuctionIdFor(
    nftContract: string,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMinBidAmount(
    auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getWtfuelAddress(overrides?: CallOverrides): Promise<string>;

  protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

  rolesManager(overrides?: CallOverrides): Promise<string>;

  setDefaultTreasury(
    _defaultTreasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProtocolFee(
    _protocolFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenTreasury(
    token: string,
    _treasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  treasuries(arg0: string, overrides?: CallOverrides): Promise<string>;

  updateAuction(
    auctionId: BigNumberish,
    reservePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createAuction(
      nftContract: string,
      tokenId: BigNumberish,
      reservePrice: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    defaultTreasury(overrides?: CallOverrides): Promise<string>;

    finalizeAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<ExchangeAuction.AuctionStructOutput>;

    getAuctionIdFor(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinBidAmount(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWtfuelAddress(overrides?: CallOverrides): Promise<string>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    rolesManager(overrides?: CallOverrides): Promise<string>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<string>;

    updateAuction(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AuctionCancelled(uint256)"(
      auctionId?: BigNumberish | null
    ): AuctionCancelledEventFilter;
    AuctionCancelled(
      auctionId?: BigNumberish | null
    ): AuctionCancelledEventFilter;

    "AuctionCreated(address,address,uint256,uint256,uint256,uint256,uint256)"(
      seller?: string | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      startTime?: null,
      endTime?: null,
      reservePrice?: null,
      auctionId?: null
    ): AuctionCreatedEventFilter;
    AuctionCreated(
      seller?: string | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      startTime?: null,
      endTime?: null,
      reservePrice?: null,
      auctionId?: null
    ): AuctionCreatedEventFilter;

    "AuctionFinalized(uint256,address,address,uint256,uint256,uint256)"(
      auctionId?: BigNumberish | null,
      seller?: string | null,
      bidder?: string | null,
      protocolFeeAmount?: null,
      royaltyAmount?: null,
      ownerRevenue?: null
    ): AuctionFinalizedEventFilter;
    AuctionFinalized(
      auctionId?: BigNumberish | null,
      seller?: string | null,
      bidder?: string | null,
      protocolFeeAmount?: null,
      royaltyAmount?: null,
      ownerRevenue?: null
    ): AuctionFinalizedEventFilter;

    "AuctionInvalidated(uint256)"(
      auctionId?: BigNumberish | null
    ): AuctionInvalidatedEventFilter;
    AuctionInvalidated(
      auctionId?: BigNumberish | null
    ): AuctionInvalidatedEventFilter;

    "AuctionUpdated(uint256,uint256)"(
      auctionId?: BigNumberish | null,
      reservePrice?: null
    ): AuctionUpdatedEventFilter;
    AuctionUpdated(
      auctionId?: BigNumberish | null,
      reservePrice?: null
    ): AuctionUpdatedEventFilter;

    "NewBid(uint256,address,uint256,uint256)"(
      auctionId?: BigNumberish | null,
      bidder?: string | null,
      amount?: null,
      endTime?: null
    ): NewBidEventFilter;
    NewBid(
      auctionId?: BigNumberish | null,
      bidder?: string | null,
      amount?: null,
      endTime?: null
    ): NewBidEventFilter;

    "TransferProxyUpdated(string,address)"(
      assetType?: null,
      proxy?: null
    ): TransferProxyUpdatedEventFilter;
    TransferProxyUpdated(
      assetType?: null,
      proxy?: null
    ): TransferProxyUpdatedEventFilter;

    "TransferToWTfuelExchange(address,uint256)"(
      user?: string | null,
      amount?: null
    ): TransferToWTfuelExchangeEventFilter;
    TransferToWTfuelExchange(
      user?: string | null,
      amount?: null
    ): TransferToWTfuelExchangeEventFilter;
  };

  estimateGas: {
    bid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createAuction(
      nftContract: string,
      tokenId: BigNumberish,
      reservePrice: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    defaultTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    finalizeAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuctionIdFor(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinBidAmount(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWtfuelAddress(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    rolesManager(overrides?: CallOverrides): Promise<BigNumber>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    updateAuction(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bid(
      auctionId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createAuction(
      nftContract: string,
      tokenId: BigNumberish,
      reservePrice: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    defaultTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    finalizeAuction(
      auctionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAuction(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAuctionIdFor(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinBidAmount(
      auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWtfuelAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rolesManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    treasuries(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateAuction(
      auctionId: BigNumberish,
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
