/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface ExchangeOfferInterface extends utils.Interface {
  functions: {
    "acceptOffer(address,uint256,address,uint256)": FunctionFragment;
    "defaultTreasury()": FunctionFragment;
    "getMinOfferAmount(address,uint256)": FunctionFragment;
    "getOffer(address,uint256)": FunctionFragment;
    "getWtfuelAddress()": FunctionFragment;
    "makeOffer(address,uint256,uint256)": FunctionFragment;
    "protocolFee()": FunctionFragment;
    "rolesManager()": FunctionFragment;
    "setDefaultTreasury(address)": FunctionFragment;
    "setProtocolFee(uint256)": FunctionFragment;
    "setTokenTreasury(address,address)": FunctionFragment;
    "treasuries(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptOffer"
      | "defaultTreasury"
      | "getMinOfferAmount"
      | "getOffer"
      | "getWtfuelAddress"
      | "makeOffer"
      | "protocolFee"
      | "rolesManager"
      | "setDefaultTreasury"
      | "setProtocolFee"
      | "setTokenTreasury"
      | "treasuries"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOffer",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMinOfferAmount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWtfuelAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "makeOffer",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rolesManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultTreasury",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenTreasury",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "treasuries", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "acceptOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinOfferAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWtfuelAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "makeOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rolesManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasuries", data: BytesLike): Result;

  events: {
    "NewOffer(address,uint256,address,uint256,uint256)": EventFragment;
    "OfferAccepted(address,uint256,address,address,uint256,uint256,uint256)": EventFragment;
    "OfferCancelledByAdmin(address,uint256,string)": EventFragment;
    "OfferInvalidated(address,uint256)": EventFragment;
    "TransferProxyUpdated(string,address)": EventFragment;
    "TransferToWTfuelExchange(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferCancelledByAdmin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferInvalidated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferProxyUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferToWTfuelExchange"): EventFragment;
}

export interface NewOfferEventObject {
  nftContract: string;
  tokenId: BigNumber;
  buyer: string;
  amount: BigNumber;
  expiration: BigNumber;
}
export type NewOfferEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, BigNumber],
  NewOfferEventObject
>;

export type NewOfferEventFilter = TypedEventFilter<NewOfferEvent>;

export interface OfferAcceptedEventObject {
  nftContract: string;
  tokenId: BigNumber;
  buyer: string;
  seller: string;
  protocolFeeAmount: BigNumber;
  royaltyAmount: BigNumber;
  ownerRevenue: BigNumber;
}
export type OfferAcceptedEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber, BigNumber, BigNumber],
  OfferAcceptedEventObject
>;

export type OfferAcceptedEventFilter = TypedEventFilter<OfferAcceptedEvent>;

export interface OfferCancelledByAdminEventObject {
  nftContract: string;
  tokenId: BigNumber;
  reason: string;
}
export type OfferCancelledByAdminEvent = TypedEvent<
  [string, BigNumber, string],
  OfferCancelledByAdminEventObject
>;

export type OfferCancelledByAdminEventFilter =
  TypedEventFilter<OfferCancelledByAdminEvent>;

export interface OfferInvalidatedEventObject {
  nftContract: string;
  tokenId: BigNumber;
}
export type OfferInvalidatedEvent = TypedEvent<
  [string, BigNumber],
  OfferInvalidatedEventObject
>;

export type OfferInvalidatedEventFilter =
  TypedEventFilter<OfferInvalidatedEvent>;

export interface TransferProxyUpdatedEventObject {
  assetType: string;
  proxy: string;
}
export type TransferProxyUpdatedEvent = TypedEvent<
  [string, string],
  TransferProxyUpdatedEventObject
>;

export type TransferProxyUpdatedEventFilter =
  TypedEventFilter<TransferProxyUpdatedEvent>;

export interface TransferToWTfuelExchangeEventObject {
  user: string;
  amount: BigNumber;
}
export type TransferToWTfuelExchangeEvent = TypedEvent<
  [string, BigNumber],
  TransferToWTfuelExchangeEventObject
>;

export type TransferToWTfuelExchangeEventFilter =
  TypedEventFilter<TransferToWTfuelExchangeEvent>;

export interface ExchangeOffer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ExchangeOfferInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOffer(
      nftContract: string,
      tokenId: BigNumberish,
      offerFrom: string,
      minAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    defaultTreasury(overrides?: CallOverrides): Promise<[string]>;

    getMinOfferAmount(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { minimum: BigNumber }>;

    getOffer(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        buyer: string;
        expiration: BigNumber;
        amount: BigNumber;
      }
    >;

    getWtfuelAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { wtfuelAddress: string }>;

    makeOffer(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    protocolFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    rolesManager(overrides?: CallOverrides): Promise<[string]>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<[string]>;
  };

  acceptOffer(
    nftContract: string,
    tokenId: BigNumberish,
    offerFrom: string,
    minAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  defaultTreasury(overrides?: CallOverrides): Promise<string>;

  getMinOfferAmount(
    nftContract: string,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getOffer(
    nftContract: string,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      buyer: string;
      expiration: BigNumber;
      amount: BigNumber;
    }
  >;

  getWtfuelAddress(overrides?: CallOverrides): Promise<string>;

  makeOffer(
    nftContract: string,
    tokenId: BigNumberish,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

  rolesManager(overrides?: CallOverrides): Promise<string>;

  setDefaultTreasury(
    _defaultTreasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProtocolFee(
    _protocolFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenTreasury(
    token: string,
    _treasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  treasuries(arg0: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    acceptOffer(
      nftContract: string,
      tokenId: BigNumberish,
      offerFrom: string,
      minAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    defaultTreasury(overrides?: CallOverrides): Promise<string>;

    getMinOfferAmount(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOffer(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        buyer: string;
        expiration: BigNumber;
        amount: BigNumber;
      }
    >;

    getWtfuelAddress(overrides?: CallOverrides): Promise<string>;

    makeOffer(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    rolesManager(overrides?: CallOverrides): Promise<string>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "NewOffer(address,uint256,address,uint256,uint256)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null,
      amount?: null,
      expiration?: null
    ): NewOfferEventFilter;
    NewOffer(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null,
      amount?: null,
      expiration?: null
    ): NewOfferEventFilter;

    "OfferAccepted(address,uint256,address,address,uint256,uint256,uint256)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null,
      seller?: null,
      protocolFeeAmount?: null,
      royaltyAmount?: null,
      ownerRevenue?: null
    ): OfferAcceptedEventFilter;
    OfferAccepted(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null,
      seller?: null,
      protocolFeeAmount?: null,
      royaltyAmount?: null,
      ownerRevenue?: null
    ): OfferAcceptedEventFilter;

    "OfferCancelledByAdmin(address,uint256,string)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      reason?: null
    ): OfferCancelledByAdminEventFilter;
    OfferCancelledByAdmin(
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      reason?: null
    ): OfferCancelledByAdminEventFilter;

    "OfferInvalidated(address,uint256)"(
      nftContract?: string | null,
      tokenId?: BigNumberish | null
    ): OfferInvalidatedEventFilter;
    OfferInvalidated(
      nftContract?: string | null,
      tokenId?: BigNumberish | null
    ): OfferInvalidatedEventFilter;

    "TransferProxyUpdated(string,address)"(
      assetType?: null,
      proxy?: null
    ): TransferProxyUpdatedEventFilter;
    TransferProxyUpdated(
      assetType?: null,
      proxy?: null
    ): TransferProxyUpdatedEventFilter;

    "TransferToWTfuelExchange(address,uint256)"(
      user?: string | null,
      amount?: null
    ): TransferToWTfuelExchangeEventFilter;
    TransferToWTfuelExchange(
      user?: string | null,
      amount?: null
    ): TransferToWTfuelExchangeEventFilter;
  };

  estimateGas: {
    acceptOffer(
      nftContract: string,
      tokenId: BigNumberish,
      offerFrom: string,
      minAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    defaultTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    getMinOfferAmount(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOffer(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWtfuelAddress(overrides?: CallOverrides): Promise<BigNumber>;

    makeOffer(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    rolesManager(overrides?: CallOverrides): Promise<BigNumber>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    treasuries(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOffer(
      nftContract: string,
      tokenId: BigNumberish,
      offerFrom: string,
      minAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    defaultTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMinOfferAmount(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOffer(
      nftContract: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWtfuelAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    makeOffer(
      nftContract: string,
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    protocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rolesManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDefaultTreasury(
      _defaultTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFee(
      _protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenTreasury(
      token: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    treasuries(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
