/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155 from "./erc1155";
export type { erc1155 };
import type * as erc721 from "./erc721";
export type { erc721 };
